# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: h:/FPGA/VGA/blase/blase.srcs/sources_1/bd/blaze/ip/blaze_processing_system7_0_1/blaze_processing_system7_0_1.xci
# IP: The module: 'blaze_processing_system7_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: h:/FPGA/VGA/blase/blase.srcs/sources_1/bd/blaze/ip/blaze_processing_system7_0_1/blaze_processing_system7_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'blaze_processing_system7_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: h:/FPGA/VGA/blase/blase.srcs/sources_1/bd/blaze/ip/blaze_processing_system7_0_1/blaze_processing_system7_0_1.xci
# IP: The module: 'blaze_processing_system7_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: h:/FPGA/VGA/blase/blase.srcs/sources_1/bd/blaze/ip/blaze_processing_system7_0_1/blaze_processing_system7_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'blaze_processing_system7_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
