# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
set_msg_config  -ruleid {1}  -id {[BD 41-1306]}  -suppress 
set_msg_config  -ruleid {2}  -id {[BD 41-1271]}  -suppress 
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir H:/FPGA/VGA/blase/blase.cache/wt [current_project]
set_property parent.project_path H:/FPGA/VGA/blase/blase.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo h:/FPGA/VGA/blase/blase.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib H:/FPGA/VGA/blase/blase.srcs/sources_1/bd/blaze/hdl/blaze_wrapper.v
add_files H:/FPGA/VGA/blase/blase.srcs/sources_1/bd/blaze/blaze.bd
set_property used_in_implementation false [get_files -all h:/FPGA/VGA/blase/blase.srcs/sources_1/bd/blaze/ip/blaze_microblaze_0_1/blaze_microblaze_0_1.xdc]
set_property used_in_implementation false [get_files -all h:/FPGA/VGA/blase/blase.srcs/sources_1/bd/blaze/ip/blaze_microblaze_0_1/blaze_microblaze_0_1_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all h:/FPGA/VGA/blase/blase.srcs/sources_1/bd/blaze/ip/blaze_microblaze_0_1/blaze_microblaze_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all h:/FPGA/VGA/blase/blase.srcs/sources_1/bd/blaze/ip/blaze_mdm_1_1/blaze_mdm_1_1.xdc]
set_property used_in_implementation false [get_files -all h:/FPGA/VGA/blase/blase.srcs/sources_1/bd/blaze/ip/blaze_mdm_1_1/blaze_mdm_1_1_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all h:/FPGA/VGA/blase/blase.srcs/sources_1/bd/blaze/ip/blaze_clk_wiz_1_1/blaze_clk_wiz_1_1_board.xdc]
set_property used_in_implementation false [get_files -all h:/FPGA/VGA/blase/blase.srcs/sources_1/bd/blaze/ip/blaze_clk_wiz_1_1/blaze_clk_wiz_1_1.xdc]
set_property used_in_implementation false [get_files -all h:/FPGA/VGA/blase/blase.srcs/sources_1/bd/blaze/ip/blaze_clk_wiz_1_1/blaze_clk_wiz_1_1_ooc.xdc]
set_property used_in_implementation false [get_files -all h:/FPGA/VGA/blase/blase.srcs/sources_1/bd/blaze/ip/blaze_rst_clk_wiz_1_100M_1/blaze_rst_clk_wiz_1_100M_1_board.xdc]
set_property used_in_implementation false [get_files -all h:/FPGA/VGA/blase/blase.srcs/sources_1/bd/blaze/ip/blaze_rst_clk_wiz_1_100M_1/blaze_rst_clk_wiz_1_100M_1.xdc]
set_property used_in_implementation false [get_files -all h:/FPGA/VGA/blase/blase.srcs/sources_1/bd/blaze/ip/blaze_rst_clk_wiz_1_100M_1/blaze_rst_clk_wiz_1_100M_1_ooc.xdc]
set_property used_in_implementation false [get_files -all h:/FPGA/VGA/blase/blase.srcs/sources_1/bd/blaze/ip/blaze_axi_gpio_0_0/blaze_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all h:/FPGA/VGA/blase/blase.srcs/sources_1/bd/blaze/ip/blaze_axi_gpio_0_0/blaze_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all h:/FPGA/VGA/blase/blase.srcs/sources_1/bd/blaze/ip/blaze_axi_gpio_0_0/blaze_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all h:/FPGA/VGA/blase/blase.srcs/sources_1/bd/blaze/ip/blaze_axi_uartlite_0_0/blaze_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all h:/FPGA/VGA/blase/blase.srcs/sources_1/bd/blaze/ip/blaze_axi_uartlite_0_0/blaze_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all h:/FPGA/VGA/blase/blase.srcs/sources_1/bd/blaze/ip/blaze_axi_uartlite_0_0/blaze_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all h:/FPGA/VGA/blase/blase.srcs/sources_1/bd/blaze/ip/blaze_processing_system7_0_1/blaze_processing_system7_0_1.xdc]
set_property used_in_implementation false [get_files -all h:/FPGA/VGA/blase/blase.srcs/sources_1/bd/blaze/ip/blaze_rst_ps7_0_100M_0/blaze_rst_ps7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all h:/FPGA/VGA/blase/blase.srcs/sources_1/bd/blaze/ip/blaze_rst_ps7_0_100M_0/blaze_rst_ps7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all h:/FPGA/VGA/blase/blase.srcs/sources_1/bd/blaze/ip/blaze_rst_ps7_0_100M_0/blaze_rst_ps7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all h:/FPGA/VGA/blase/blase.srcs/sources_1/bd/blaze/ip/blaze_xbar_0/blaze_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all h:/FPGA/VGA/blase/blase.srcs/sources_1/bd/blaze/ip/blaze_dlmb_v10_2/blaze_dlmb_v10_2.xdc]
set_property used_in_implementation false [get_files -all h:/FPGA/VGA/blase/blase.srcs/sources_1/bd/blaze/ip/blaze_dlmb_v10_2/blaze_dlmb_v10_2_ooc.xdc]
set_property used_in_implementation false [get_files -all h:/FPGA/VGA/blase/blase.srcs/sources_1/bd/blaze/ip/blaze_ilmb_v10_2/blaze_ilmb_v10_2.xdc]
set_property used_in_implementation false [get_files -all h:/FPGA/VGA/blase/blase.srcs/sources_1/bd/blaze/ip/blaze_ilmb_v10_2/blaze_ilmb_v10_2_ooc.xdc]
set_property used_in_implementation false [get_files -all h:/FPGA/VGA/blase/blase.srcs/sources_1/bd/blaze/ip/blaze_dlmb_bram_if_cntlr_2/blaze_dlmb_bram_if_cntlr_2_ooc.xdc]
set_property used_in_implementation false [get_files -all h:/FPGA/VGA/blase/blase.srcs/sources_1/bd/blaze/ip/blaze_ilmb_bram_if_cntlr_2/blaze_ilmb_bram_if_cntlr_2_ooc.xdc]
set_property used_in_implementation false [get_files -all h:/FPGA/VGA/blase/blase.srcs/sources_1/bd/blaze/ip/blaze_lmb_bram_2/blaze_lmb_bram_2_ooc.xdc]
set_property used_in_synthesis false [get_files -all h:/FPGA/VGA/blase/blase.srcs/sources_1/bd/blaze/ip/blaze_auto_cc_0/blaze_auto_cc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all h:/FPGA/VGA/blase/blase.srcs/sources_1/bd/blaze/ip/blaze_auto_cc_0/blaze_auto_cc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all h:/FPGA/VGA/blase/blase.srcs/sources_1/bd/blaze/ip/blaze_auto_cc_0/blaze_auto_cc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all h:/FPGA/VGA/blase/blase.srcs/sources_1/bd/blaze/ip/blaze_auto_pc_0/blaze_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all H:/FPGA/VGA/blase/blase.srcs/sources_1/bd/blaze/blaze_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc H:/FPGA/VGA/blase/blase.srcs/constrs_1/new/io.xdc
set_property used_in_implementation false [get_files H:/FPGA/VGA/blase/blase.srcs/constrs_1/new/io.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top blaze_wrapper -part xc7z010clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef blaze_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file blaze_wrapper_utilization_synth.rpt -pb blaze_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
