# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/io.xdc

# Block Designs: bd/blaze/blaze.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blaze || ORIG_REF_NAME==blaze} -quiet] -quiet

# IP: bd/blaze/ip/blaze_microblaze_0_1/blaze_microblaze_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blaze_microblaze_0_1 || ORIG_REF_NAME==blaze_microblaze_0_1} -quiet] -quiet

# IP: bd/blaze/ip/blaze_mdm_1_1/blaze_mdm_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blaze_mdm_1_1 || ORIG_REF_NAME==blaze_mdm_1_1} -quiet] -quiet

# IP: bd/blaze/ip/blaze_clk_wiz_1_1/blaze_clk_wiz_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blaze_clk_wiz_1_1 || ORIG_REF_NAME==blaze_clk_wiz_1_1} -quiet] -quiet

# IP: bd/blaze/ip/blaze_rst_clk_wiz_1_100M_1/blaze_rst_clk_wiz_1_100M_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blaze_rst_clk_wiz_1_100M_1 || ORIG_REF_NAME==blaze_rst_clk_wiz_1_100M_1} -quiet] -quiet

# IP: bd/blaze/ip/blaze_axi_gpio_0_0/blaze_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blaze_axi_gpio_0_0 || ORIG_REF_NAME==blaze_axi_gpio_0_0} -quiet] -quiet

# IP: bd/blaze/ip/blaze_microblaze_0_axi_periph_0/blaze_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blaze_microblaze_0_axi_periph_0 || ORIG_REF_NAME==blaze_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/blaze/ip/blaze_axi_uartlite_0_0/blaze_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blaze_axi_uartlite_0_0 || ORIG_REF_NAME==blaze_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/blaze/ip/blaze_processing_system7_0_1/blaze_processing_system7_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blaze_processing_system7_0_1 || ORIG_REF_NAME==blaze_processing_system7_0_1} -quiet] -quiet

# IP: bd/blaze/ip/blaze_xlconstant_0_0/blaze_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blaze_xlconstant_0_0 || ORIG_REF_NAME==blaze_xlconstant_0_0} -quiet] -quiet

# IP: bd/blaze/ip/blaze_rst_ps7_0_100M_0/blaze_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blaze_rst_ps7_0_100M_0 || ORIG_REF_NAME==blaze_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/blaze/ip/blaze_xbar_0/blaze_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blaze_xbar_0 || ORIG_REF_NAME==blaze_xbar_0} -quiet] -quiet

# IP: bd/blaze/ip/blaze_dlmb_v10_2/blaze_dlmb_v10_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blaze_dlmb_v10_2 || ORIG_REF_NAME==blaze_dlmb_v10_2} -quiet] -quiet

# IP: bd/blaze/ip/blaze_ilmb_v10_2/blaze_ilmb_v10_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blaze_ilmb_v10_2 || ORIG_REF_NAME==blaze_ilmb_v10_2} -quiet] -quiet

# IP: bd/blaze/ip/blaze_dlmb_bram_if_cntlr_2/blaze_dlmb_bram_if_cntlr_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blaze_dlmb_bram_if_cntlr_2 || ORIG_REF_NAME==blaze_dlmb_bram_if_cntlr_2} -quiet] -quiet

# IP: bd/blaze/ip/blaze_ilmb_bram_if_cntlr_2/blaze_ilmb_bram_if_cntlr_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blaze_ilmb_bram_if_cntlr_2 || ORIG_REF_NAME==blaze_ilmb_bram_if_cntlr_2} -quiet] -quiet

# IP: bd/blaze/ip/blaze_lmb_bram_2/blaze_lmb_bram_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blaze_lmb_bram_2 || ORIG_REF_NAME==blaze_lmb_bram_2} -quiet] -quiet

# IP: bd/blaze/ip/blaze_auto_cc_0/blaze_auto_cc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blaze_auto_cc_0 || ORIG_REF_NAME==blaze_auto_cc_0} -quiet] -quiet

# IP: bd/blaze/ip/blaze_auto_pc_0/blaze_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blaze_auto_pc_0 || ORIG_REF_NAME==blaze_auto_pc_0} -quiet] -quiet

# XDC: bd/blaze/blaze_ooc.xdc
